### ISSUE TITLE
Column heading with "/" fails to display values in the grid

### ISSUE THREAD

**Issue by JakeK-MBIA** [jdhitsolutions/PSScriptTools#108]
Given a simple object:

$myObject = [PSCustomObject]@{
    Name     = 'Kevin'
    'blah/2' = 'PowerShell'
    State    = 'Texas'
}

$myObject | ConvertTo-WPFGrid

Column values with forward slash "/" fails to show in the grid.

![image](https://user-images.githubusercontent.com/83593255/122858102-b1f78880-d2e7-11eb-9044-2e4ef97b64a0.png)

PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by jdhitsolutions** [comment]
I suppose technically using a slash is legal. But definitely non-standard. I'll have to dig into this.

**Comment by jdhitsolutions** [comment]
This is a problem with autogenerated columns as I am doing with this command. https://social.msdn.microsoft.com/Forums/sqlserver/en-US/f5f752f6-f08d-4d46-9e1e-78a4496eaf12/why-does-not-datagrid-show-values-if-there-are-a-point-82208221-or-82208221-in-header?forum=wpf  Modifying the code to meet this edge case may require more work than is justified. But I will look.

**Comment by jdhitsolutions** [comment]
I think I have an updated version for the next release that will fix this. Until then, avoid using slashes or periods.

**Comment by JakeK-MBIA** [comment]
That is awesome!  Thanks so much for your work and effort.  Big fan!

**Comment by jdhitsolutions** [comment]
Update the module to v2.37.0 and this should fix the problem.

**Comment by JakeK-MBIA** [comment]
Very nicely done.  It works now.  Thank you very much.

![image](https://user-images.githubusercontent.com/83593255/123167308-5f7fae80-d444-11eb-9515-5583d7c9a644.png)
