### ISSUE TITLE
Get-ModuleCommand should (optionally?) look at Value in ExportedCommands

### ISSUE THREAD

**Issue by cdhunt** [jdhitsolutions/PSScriptTools#112]
**Is your feature request related to a problem? Please describe.**
I have a module that uses a DefaultCommandPrefix to disambiguate from built-in cmdlet names. Get-ModuleCommand operates on the key which is the command name before applying the prefix. This causes it to query info on the built-in command versus my command.

Example:

`DefaultCommandPrefix = 'my'`
`New-Service` vs `New-myService`

I want info on `New-myService`

**Describe the solution you'd like**
If `Key -ne Value`, use `Value` in [Get-ModuleCommand.ps1#L53](https://github.com/jdhitsolutions/PSScriptTools/blob/master/functions/Get-ModuleCommand.ps1#L53)

**Describe alternatives you've considered**
I don't see anywhere that `DefaultCommandPrefix` is exposed to the runtime so you can programmatically check.

I believe you could also always just use Value instead of Key.

**Additional context**

```dos
Get-Module myModule| Select-Object -ExpandProperty ExportedCommands


Key                      Value
---                      -----
Get-Client               Get-myClient
Get-Config               Get-myConfig
Get-CurrentContext       Get-myCurrentContext
Get-Namespace            Get-myNamespace
Get-Service              Get-myService
New-Namespace            New-myNamespace
New-Service              New-myService
New-ServicePort          New-myServicePort
New-ServiceSpec          New-myServiceSpec
Remove-Namespace         Remove-myNamespace
Remove-Service           Remove-myService
Set-Namespace            Set-myNamespace
Set-Service              Set-myService
```

```dos
Get-ModuleCommand

   ModuleName: myModule

Name                     Alias      Synopsis
----                     -----      --------
Get-Service              gsv        Gets the services on the computer.
New-Service                         Creates a new Windows service.
Remove-Service                      Removes a Windows service.
Set-Service                         Starts, stops, and suspends a service, and changes its properties.
```

**Comment by cdhunt** [comment]
After poking around `ExportedCommands` for a few minutes I can't track down what is generating the name with prefix. The prefix or prefixed name doesn't seem to be in `CmdletInfo`. Pesky FormatData.

**Comment by jdhitsolutions** [comment]
What version of PowerShell are you running this under? I modified a module to use a default prefix and this works in 5.1.

![image](https://user-images.githubusercontent.com/12089920/124952455-40efea80-dfe2-11eb-9493-f5294b2cebc0.png)


It also works in PS 7 if the module is *loaded*

![image](https://user-images.githubusercontent.com/12089920/124952479-477e6200-dfe2-11eb-9eef-3902c5aff8f9.png)

But there is a problem if it isn't loaded.

![image](https://user-images.githubusercontent.com/12089920/124952602-62e96d00-dfe2-11eb-874f-dcd0b9f33000.png)

But only in PowerShell 7. Windows PowerShell works fine.

**Comment by cdhunt** [comment]
Yeah, I'm running in 7.

**Comment by jdhitsolutions** [comment]
This looks like a PowerShell 7 bug with `Get-Module`. Investigating.

**Comment by jdhitsolutions** [comment]
Microsoft agrees that this is a bug in PowerShell 7. The workaround for us appears to be first import the module then run `Get-ModuleCommand`.

**Comment by jdhitsolutions** [comment]
This is still a bug in PowerShell 7.2.

**Comment by jdhitsolutions** [comment]
Is this still an issue for you? It has been a while since this was opened.

**Comment by cdhunt** [comment]
I'm not currently using this module. I can't say.

**Comment by jdhitsolutions** [comment]
I think I'm going to close the issue then. We can always re-open it or start anew.
