### ISSUE TITLE
ConvertTo-Markdown add '-Transpose' option to the -AsTable parameter

### ISSUE THREAD

**Issue by martincaddick** [jdhitsolutions/PSScriptTools#114]
**Is your feature request related to a problem? Please describe.**
No problem, feature request

**Describe the solution you'd like**
Running this command produces the desired details however I get a 1 row, _very_ wide table. It would be awesome to be able to pass an additional parameter of -Transpose that would convert the columns to rows
Get-SPOTenant | ConvertTo-MDTest -AsTable -Title "SharePoint" -PreContent "url of the SharePoint admin page" | Add-Content -Path .\SharePoint365.md

**Describe alternatives you've considered**
I've previously used PSWriteWord with the -transpose switch that produced the desired outcome but I want to output in markdown tables. https://github.com/EvotecIT/PSWriteWord/blob/master/README.md 

**Additional context**
![image](https://user-images.githubusercontent.com/73564857/134083729-3d77405c-0666-4f35-8613-3f8e286fd008.png)

**Comment by jdhitsolutions** [comment]
I'll take a look.

**Comment by jdhitsolutions** [comment]
I finally got a chance to look at this. The default output is a list. The `AsTable` parameter allows you to force a table if you know it will fit your needs.

![image](https://user-images.githubusercontent.com/12089920/144068350-cffab1a2-bb7d-411e-aa99-21b95a355f7a.png)

I think if you run your command without `AsTable` you'll get the results you are expecting.

**Comment by jdhitsolutions** [comment]
Markdown lists don't really have any sort of style as a table.

![image](https://user-images.githubusercontent.com/12089920/144068871-b3f475e7-705f-4c5d-877f-bf3975f0df3b.png)

**Comment by jdhitsolutions** [comment]
But maybe...after playing a bit with markdown, this might be what you are after.

|   |   |
|---|---|
| __Id__        | 37920 |
__Handles__   | 951 |
__WS__        | 206761984 |
__PM__        | 153714688 |
__Name__      | pwsh |
__Path__      | C:\Program Files\PowerShell\7\pwsh.exe |
__StartTime__ | 11/30/2021 9:05:28 AM |

Although there's no way to suppress that blank column headings.

**Comment by jdhitsolutions** [comment]
Yet another option, but I don't think there is a way to force alignment.

__Id__        : 37920<br>
__Handles__   : 951<br>
__WS__        : 206761984<br>
__PM__        : 153714688<br>
__Name__      : pwsh<br>
__Path__      : C:\Program Files\PowerShell\7\pwsh.exe<br>
__StartTime__ : 11/30/2021 9:05:28 AM<br>

**Comment by jdhitsolutions** [comment]
I've added support for this in v2.40.0 of the module,
