### ISSUE TITLE
get-whois fails on valid IP address

### ISSUE THREAD

**Issue by DaveCurr** [jdhitsolutions/PSScriptTools#117]
The octet verifiction checks to see if each one is >254, and fails if they are. 255 is valid as part of an IP address (even if used as the broadcast address).   Suggest (for simplicity's sake) just changing the check to 255, rather than worry about CIDR subnetting..

**Comment by jdhitsolutions** [comment]
You must be referring to the parameter validation. Technically, I know an address can include 255. But are there really any registered addresses in the ARIN database that use 255?

**Comment by DaveCurr** [comment]
This isn't the one that drew my attention today, but it will suffice:
NetRange:       167.255.0.0 - 167.255.255.255
CIDR:           167.255.0.0/16
NetName:        VIEWPORT
NetHandle:      NET-167-255-0-0-1
Parent:         NET167 (NET-167-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       
Organization:   Vuteq Engineering Corporation (VEC-1)
RegDate:        1993-11-30
Updated:        2021-12-14
Ref:            https://rdap.arin.net/registry/ip/167.255.0.0

**Comment by jdhitsolutions** [comment]
Got it. This gives me something to test with. This is a simple enough fix to roll into the next release.

**Comment by jdhitsolutions** [comment]
I fixed this in v2.40.0 of the module if you want to update and verify.

![image](https://user-images.githubusercontent.com/12089920/148830259-531adfb1-df28-4141-9818-9c03bc751c79.png)

**Comment by DaveCurr** [comment]
Works great - many thanks



________________________________
