### ISSUE TITLE
[Bug]: Get-WindowsVersion/Get-WindowsVersionString on non-English based systems

### ISSUE THREAD

**Issue by t0rsten** [jdhitsolutions/PSScriptTools#142]
### Describe the problem

On a non-English speaking system (in my case German) the following error message occurs.

![2023-10-20_03h44_36](https://github.com/jdhitsolutions/PSScriptTools/assets/46536955/fceebed7-4c36-40bd-82f9-64a0f3ad38bb)

The reason is that `systeminfo.exe` is fully translated.

![2023-10-20_03h43_37](https://github.com/jdhitsolutions/PSScriptTools/assets/46536955/e96ad28a-c1a9-40b2-b532-5055939d908b)

### Additional Information

From my point of view, `systeminfo.exe` should not be used and the WMI class `Win32_OperatingSystem` should be used instead.

`(Get-CimInstance -ClassName Win32_OperatingSystem -Property Caption).Caption`

### PowerShell version

7.3

### Platform

Windows 10 Pro or Enterprise

### Additional Checks

- [X] You are using the latest version of this module.
- [X] You have read this repository's README file.
- [X] You have read full help and examples for the command you are having problems with.
- [ ] You are running PowerShell in an elevated session.
- [X] You are running in a traditional PowerShell console or Windows Terminal

**Comment by jdhitsolutions** [comment]
I will take a look when I am back home. I think I went with the tool because it gave me extra time info. But it has been a long time since I have looked at the command.

**Comment by jdhitsolutions** [comment]
I finally got a little free time to look at this. I see what is happening now. I will have to get creative here.

**Comment by jdhitsolutions** [comment]
I think I will have something in the next release for you to try.

**Comment by t0rsten** [comment]
Let me know when I can test it.

**Comment by jdhitsolutions** [comment]
I have published 2.49.0 to the PowerShell Gallery if you want to update and test.

**Comment by t0rsten** [comment]
Problem solved. Thanks a lot!

**Comment by t0rsten** [comment]
Problem solved. Thanks a lot!
