### ISSUE TITLE
Clean up runspace from ConvertTo-WPFGrid

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/PSScriptTools#25]
Starting in v2.0.0 `ConvertTo-WPFGrid` now lives in a separate runspace to avoid blocking the PowerShell prompt. I'd love to find a way to automatically remove the runspace when the form is closed.

**Comment by scriptingstudio** [comment]
My guess.
Native OGV is a code working in the child ps host. I am sure .net has classes to create ps host. And you can do everything you want there.

**Comment by jdhitsolutions** [comment]
I have no idea other than that is above my pay grade.

**Comment by jdhitsolutions** [comment]
Handled in v2.13.0
