### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by scriptingstudio** [jdhitsolutions/PSScriptTools#34]
Add Refresh button to the form

**Comment by jdhitsolutions** [comment]
I'm assuming you mean the `ConvertTo-WPFGrid` command. It already has an option for an automatic refresh interval. What benefit would a Refresh button provide or what use case do you have in mind?

**Comment by scriptingstudio** [comment]
It could be useful when refresh interval rather long, say 15min, and I want to get new data immediately.

**Comment by jdhitsolutions** [comment]
I can I have a handle on this. Look for this feature in v2.4.0

**Comment by scriptingstudio** [comment]
It is getting better.
BUT

-      Window is not resizable at all. I expect grid size corresponds window size as I resize window.

-      No horizontal scroll although I have a wide grid.

-      Refresh button does not reset the refresh counter.

**Comment by jdhitsolutions** [comment]
Well rats. There used to be a horizontal scroll. Guess this is the Agile model - it will be better the next time.

**Comment by jdhitsolutions** [comment]
I think I've worked out the refresh button. Look changes in v2.5.0

**Comment by jdhitsolutions** [comment]
Updated in v2.5.0
