### ISSUE TITLE
Improve grid resizing in ConvertTo-WPFGrid

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/PSScriptTools#36]
When resizing the form the grid should resize with it.

**Comment by jdhitsolutions** [comment]
This should be handled in v2.4.0

**Comment by jdhitsolutions** [comment]
As of v2.5.0 I'm satisfied with how the grid and form resize. It works as i expect it to. But I'll leave this issue open for a bit in case someone wants to convince me otherwise.

**Comment by scriptingstudio** [comment]
One more issue is left. The form is still not resizable. What am I doing wrong?
I dont modify the function and call it like this:
$datapath = (resolve-path $PSscriptRoot\pcmon\pcmon.csv).path
import-csv $datapath -encoding default -delimiter ';' | ConvertTo-WPFGrid -timeout 40 -refresh -title 'PC Monitor' -var datapath
I use PS 5.1 on Windows 10 1809

**Comment by jdhitsolutions** [comment]
Do you get anything in the form? Have you tried with a different command like `get-service | select name,status,displayname | convertto-wpfgrid`

**Comment by jdhitsolutions** [comment]
Also make sure your scriptroot isn't in a profile defined PSDrive.

**Comment by scriptingstudio** [comment]
Yes my form is filled.

just tested get-service | select name,status,displayname | convertto-wpfgrid
I can resize the form horizontaly only.

**Comment by scriptingstudio** [comment]
if I dont use var import the form can be resizable horizontally.

**Comment by jdhitsolutions** [comment]
If you grab the lower right corner of the form you should be able to drag and resize in any direction.

**Comment by scriptingstudio** [comment]
Now it is true. Such a resizing style is so tricky :-))
Only angles are active and only for reducing. Is it possible to make it maximize and increase?

**Comment by jdhitsolutions** [comment]
I've set a maximum size to be a percentage of the totally available screen space. You can click the maximize windows control icon in the top right. if you have more data than that then you'll need to live with the scroll bars.

**Comment by scriptingstudio** [comment]
Maximize control does nothing useful. Maximum window size is limited in your function. 

The window size should match data size. If the data fit in the window it cannot be maximized. If the data does not fit in the screen the window can be resized any direction with data size in mind.

I have no idea if WPF form can be configured that way.

**Comment by jdhitsolutions** [comment]
Removing the limits make the form ugly to work. If you have a lot of data to display, more than will fill your available screen space, the edges of the form bleed off and it is tricky to grab something to resize. I suppose I could look at increasing the max size of the form. I think I have some work to work with.

**Comment by jdhitsolutions** [comment]
I increased the max form size in v2.6.0 which I think is about the best I can do with sizing issues.

**Comment by scriptingstudio** [comment]
works perfect.
Can you tell me what is the setting for a form to remove cell borders? I am lazy to explore documentation.

**Comment by jdhitsolutions** [comment]
I think this will modify it 

```powershell
$datagrid.GridLinesVisibility =[system.windows.controls.datagridGridLinesVisibility]::All
```

**Comment by jdhitsolutions** [comment]
I can see where that might make a nice cosmetic difference.

**Comment by jdhitsolutions** [comment]
I've added a parameter which you'll see in v2.7.0

**Comment by jdhitsolutions** [comment]
I think I've done about all I can on resizing issues for now.
