### ISSUE TITLE
out-null

### ISSUE THREAD

**Issue by scriptingstudio** [jdhitsolutions/PSScriptTools#47]
out-null cmdlet is rather slow.
Change it with [void] or $null =

**Comment by jdhitsolutions** [comment]
yeah, I know there are technical differences and that using void is better. Personally, I don't think in this module the difference is significant but I will keep it in mind for the next round of updates. Or is there a specific section of code that you feel would really benefit from the change?

**Comment by jdhitsolutions** [comment]
started changing this in v2.8.0
