### ISSUE TITLE
New-PSFormatXML: convert the parent path into a real file system path

### ISSUE THREAD

**Issue by scriptingstudio** [jdhitsolutions/PSScriptTools#48]
two line expression in the Begin block can be simplified:
$realPath = (resolve-path $path).providerPath

**Comment by jdhitsolutions** [comment]
It's a trade-off. Technically your approach is faster but the difference is negligible. An argument could be made that the code I'm using now is a bit clearer, especially for beginners.

```powershell
        #convert the parent path into a real file system path
        $parent = Convert-Path -Path (Split-Path -Path $path)
        #reconstruct the path
        $realPath = Join-Path -Path $parent -ChildPath (Split-Path -Path $path -Leaf)
```

There are often multiple ways to achieve a result in PowerShell and which path you choose may depend on more than writing the shortest code possible.

**Comment by scriptingstudio** [comment]
multistep approach sometimes confuses, but it is up to you

**Comment by scriptingstudio** [comment]
I was wrong. $path could be a new file and then resolve-path would throw unrecoverable error. So your solution is safe.
