### ISSUE TITLE
New-PSFormatXML and strange behavior

### ISSUE THREAD

**Issue by scriptingstudio** [jdhitsolutions/PSScriptTools#49]
My script runs this code many times in the same session:
```
	$TypeName = 'Custom.Monitor.ModuleSynchronization'
	$obj = [pscustomobject]@{
			PSTypeName  = $TypeName
			Node        = ''
			Type        = '' 
			Status      = ''
			Source      = ''
			Target      = ''
		}
	if (-not (get-typedata $TypeName)) {
		$p = (resolve-path "$script:PSscriptroot\..").providerPath, "$TypeName.format.ps1xml" -join '\'
		$obj | New-PSFormatXML -FormatType table -path $p
		Update-FormatData -appendpath $p
		remove-item $p -force -Confirm:$false -ea 0
	}
```

Eventually I receive the message like that: command get-ScheduledTask not found in the module ... This module cannot be loaded.
As I try to load the module manualy I receive the message like that: file ...format.ps1xml not found.
And I have to reload PS host. I think I do something wrong because of misunderstanding where my typedata is stored and how it works.

**Comment by jdhitsolutions** [comment]
It looks like you are trying to create the ps1xml file in the root directory of wherever your script is. But you are trying to manually build the path. Instead, use Join-Path

```powershell
        $here = (resolve-path "$script:PSscriptroot\..").providerPath
        $p = Join-Path -Path $here -ChildPath "$TypeName.format.ps1xml"
```
I'd start with that.

**Comment by scriptingstudio** [comment]
Yes, but result is the same and new type works well, but again, in some time my environment breaks and I dont know where to look in.

**Comment by jdhitsolutions** [comment]
There must be something else in your code that you haven't posted. You mention an error about ScheduledTask but that has nothing to do with your code snippet. `New-PSFormatXML` is working as expected so I don't think it is your problem. You may want to post your problem in the forums at PowerShell.org.

**Comment by scriptingstudio** [comment]
It may be ScheduledTask, ActiveDirectory or whatever module. Something breaks the environment and it began after I started using New-PSFormatXML. But I have not any idea about the source reason. Iam gonna explore it. Thanks.

**Comment by scriptingstudio** [comment]
BTW `$p = Join-Path -Path $here -ChildPath "$TypeName.format.ps1xml"` will throw error because "$TypeName.format.ps1xml" has NOT existed yet.

**Comment by jdhitsolutions** [comment]
The file doesn't have to exist. But variable $Typename needs a value.

```powershell
PS C:\> $here = "c:\work"

PS C:\> Join-path $here -ChildPath "$typename.format.ps1xml"
c:\work\.format.ps1xml

PS C:\> $typename = "foo"

PS C:\> Join-path $here -ChildPath "$typename.format.ps1xml"
c:\work\foo.format.ps1xml
```
Resolve-Path will fail but not Join-Path unless you attempt to resolve

```powershell
PS C:\> Join-path $here -ChildPath "$typename.format.ps1xml" -Resolve
Join-path : Cannot find path 'C:\work\foo.format.ps1xml' because it does not exist.
At line:1 char:1
+ Join-path $here -ChildPath "$typename.format.ps1xml" -Resolve
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\work\foo.format.ps1xml:String) [Join-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
```

**Comment by scriptingstudio** [comment]
Yes, you are right. I tested `join-path` with `-resolve`.
I have explored something. I use recursion and in the each next cycle `get-typedata $TypeName` failed to see the type. I dont understand why. New scope?

**Comment by jdhitsolutions** [comment]
Without seeing everything that would be a good bet. If each recursion, as you call it, is running in a new scope, then it probably won't have your custom type extensions until you create it and/or run `Update-FormatData`.

**Comment by scriptingstudio** [comment]
I have found a causer. The xml file with new format definition should **not be deleted** because new format definition lives in ps host session not just script session. As any cmdlet tries to read format definitions it cannot reload the new xml file and I get a strange error message. Sorry for my English. Explained it as I could. 
The case closed.

**Comment by jdhitsolutions** [comment]
That makes sense. I couldn't understand why you were deleting the ps1xml file. What you were doing is atypical behavior. But I'm glad you worked it all out.
