### ISSUE TITLE
Ability to pass in template into ConvertTo-Markdown

### ISSUE THREAD

**Issue by rsaa** [jdhitsolutions/PSScriptTools#51]
Hi,

Is there anyway to pass in custom template to ConvertTo-Markdown? 

One of the issues is that main content goes in "pre" tag and you cannot have links in there.

Thanks.

**Comment by jdhitsolutions** [comment]
Always open for suggestions. Can you share what you think a template would look like? How do you think it could be passed as a parameter?

**Comment by jdhitsolutions** [comment]
Still not sure what the intent is, but I'll keep it in mind. I'll close this issue for now since I have nothing I can work with.
