### ISSUE TITLE
"Sorry. This command requires a Windows platform." issue 

### ISSUE THREAD

**Issue by ViValentin** [jdhitsolutions/PSScriptTools#59]
Hello,

It seems that in version v2.13.0 you modify some code to use $isWindows standard builtin variable within some Command like New-WPFMessageBox.
It seems that $isWindows have been introduced within Powershell Core 6 (https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-7) and so all your module commands using $isWindows doesn't work anymore on previous version of Powershell
Can you please fix this

**Comment by jdhitsolutions** [comment]
Gosh dang it. I did the same silly thing with another command which I fixed in v2.14.1. I'm on it.

**Comment by jdhitsolutions** [comment]
Hopefully , I addressed all the related issues in v2.15.0 which is now in the PowerShell Gallery. I'll leave this issue open a bit for you to confirm.

**Comment by ViValentin** [comment]
I tested and it works for me.
