### ISSUE TITLE
%Hour24 issue

### ISSUE THREAD

**Issue by ViValentin** [jdhitsolutions/PSScriptTools#62]
Hello,
In FileNameTools.ps1 file you need to change line 110
        '%hour'         = "{0:hh}" -f $now
        '%hour24'       = "{0:HH}" -f $now
by
        '%hour24'       = "{0:HH}" -f $now
        '%hour'         = "{0:hh}" -f $now
In other case hour is replace and let a "24" remaining string within New-CustomFileName result string
Regards

**Comment by jdhitsolutions** [comment]
Ah... I see what is happening.

**Comment by jdhitsolutions** [comment]
This should be fixed in v2.16.0 which has been pushed to the PowerShell Gallery.

**Comment by ViValentin** [comment]
Fixed. Thanks
