### ISSUE TITLE
Get-FolderSizeInfo

### ISSUE THREAD

**Issue by scriptingstudio** [jdhitsolutions/PSScriptTools#63]
You use ` #requires -version 5.1 ` in the script but test for an old ps version. Contradiction?

**Comment by jdhitsolutions** [comment]
The function needs at least v5.1. I handle that in the module manifest and really don't need this statement. It is a hold over from stand alone development. In the function I am using a new .net class if running PS7. Does that explain it all?

**Comment by scriptingstudio** [comment]
It does. And I think that a backward compatibility is overhead.

**Comment by jdhitsolutions** [comment]
I recognize that Windows PowerShell will be in use for quite a while yet and I am trying as much as possible with this module to support Core and Desktop PowerShell editions.
