### ISSUE TITLE
ReleaseID missing from Get-WindowsVersion function

### ISSUE THREAD

**Issue by Vistaking** [jdhitsolutions/PSScriptTools#67]
Is there way to add ReleaseID to Get-WindowsVersion function ?

**Comment by jdhitsolutions** [comment]
I think so. That info is in the registry so it shouldn't be too hard to pull out.

**Comment by jdhitsolutions** [comment]
This should be fixed in v2.18.0 which has been published to the PowerShell Gallery.

**Comment by Vistaking** [comment]
Hi Jeff thank you

To grab the the file do I run install-module again

On Feb 27, 2020, at 8:39 AM, Jeff Hicks <notifications@github.com> wrote:

﻿

This should be fixed in v2.18.0 which has been published to the PowerShell Gallery.

**Comment by jdhitsolutions** [comment]
Assuming you installed from the PowerShell Gallery, run `Update-Module PSScriptTools`
